@startuml
'https://plantuml.com/sequence-diagram

autonumber
Frontend -> RESTAPI : POST /api
RESTAPI -> TODO_serivice : CcreateTask

database NoSQLDatanbase

TODO_serivice -> NoSQLDatanbase : SQL insert task



@enduml